### ISSUE TITLE
relationshipLabels ignored

### ISSUE THREAD

**Issue by shah-ovo** [KarnerTh/mermerd#58]
I have the following yaml:

```yaml
# Connection properties
connectionString: "postgres://postgres:postgres@localhost/postgres"

# Define what schemas should be used
useAllSchemas: true

selectedTables:
  - schema1.table1
  - schema1.table2
  - schema2.table1
  - schema3.table1

# Additional flags
showAllConstraints: true

showDescriptions:
  - enumValues
  - columnComments
  - notNull

showSchemaPrefix: true

relationshipLabels:
  - "schema3.table1 schema2.table1 : participates_in"
  - "schema2.table1 schema1.table2 : results_into"
  - "schema2.table1 schema1.table1 : results_into"
```

but when I run `mermerd --runConfig ./config.yaml` I don't see any labels generated. Everything else seems to be respected. What am I missing?
