### ISSUE TITLE
Combine useAllTables and ignoreTables. Currently the setting is ignored

### ISSUE THREAD

**Issue by django23** [KarnerTh/mermerd#66]
When using the config as follows:

```
schema:
  - "mydb"

useAllTables: true

ignoreTables:
  - jobs
  - cache

# Additional flags
showAllConstraints: true
encloseWithMermaidBackticks: true
outputFileName: "mermerd.md"
debug: true
omitConstraintLabels: false
omitAttributeKeys: false
showDescriptions:
  - enumValues
  - columnComments
  - notNull
showSchemaPrefix: false
schemaPrefixSeparator: "_"

```

The ignoreTables seems to be ignored.

**Comment by KarnerTh** [comment]
Thanks for the feedback, good point. Will have look.

**Comment by django23** [comment]
Hey @KarnerTh,

I tried looking at it. I don't want to point you to the wrong place, so maybe I am wrong here:

```
func (a analyzer) GetTables(db database.Connector, selectedSchemas []string) ([]database.TableDetail, error) {
	if selectedTables := a.config.SelectedTables(); len(selectedTables) > 0 {
		return util.Map2(selectedTables, func(value string) database.TableDetail {
			res, err := database.ParseTableName(value, selectedSchemas)
			if err != nil {
				logrus.Error("Could not parse table name ", value)
			}

			return res
		}), nil
	}

	a.loadingSpinner.Start("Getting tables")
	tables, err := db.GetTables(selectedSchemas)
	a.loadingSpinner.Stop()
	if err != nil {
		logrus.Error("Getting tables failed", " | ", err)
		return nil, err
	}

	if len(tables) == 0 {
		logrus.Error("No tables found")
	}

	logrus.WithField("count", len(tables)).Info("Got tables")

	if len(a.config.IgnoreTables()) > 0 {
		tables, err = a.removeIgnoredTables(tables)
		if err != nil {
			return []database.TableDetail{}, err
		}
	}

	if a.config.UseAllTables() {
		return tables, nil
	}

	tableNames := util.Map2(tables, func(table database.TableDetail) string {
		return fmt.Sprintf("%s.%s", table.Schema, table.Name)
	})
	surveyResult, err := a.questioner.AskTableQuestion(tableNames)
	if err != nil {
		return []database.TableDetail{}, err
	}
	return util.Map2(surveyResult, func(value string) database.TableDetail {
		res, err := database.ParseTableName(value, selectedSchemas)
		if err != nil {
			logrus.Error("Could not parse table name ", value)
		}

		return res
	}), nil
}
```


It seems that the IgnoreTables happens before the UseAllTables, so it should work as advertised. That is why I didn't create a pull request.
```
	if len(a.config.IgnoreTables()) > 0 {
		tables, err = a.removeIgnoredTables(tables)
		if err != nil {
			return []database.TableDetail{}, err
		}
	}

	if a.config.UseAllTables() {
		return tables, nil
	}
```

**Comment by KarnerTh** [comment]
Hi @django23  - I looked into the issue and it should work as intended. 

When run locally with the test setup it works:

this command returns all tables
```bash
go run main.go -c "postgresql://user:password@localhost:5432/mermerd_test" -s public --useAllTables --outputMode stdout
````

when we add `--ignoreTables article_comment` we get all tables except the specified one 
```bash
go run main.go -c "postgresql://user:password@localhost:5432/mermerd_test" -s public --useAllTables --outputMode stdout --ignoreTables article_comment
```

I also tested it via your config file and with the test db it seems to also work:
```yaml
connectionString: "postgresql://user:password@localhost:5432/mermerd_test"
schema:
  - public
useAllTables: true
ignoreTables:
  - article_comment

# Additional flags
showAllConstraints: true
encloseWithMermaidBackticks: true
outputFileName: "testresult.md"
debug: true
omitConstraintLabels: false
omitAttributeKeys: false
showDescriptions:
  - enumValues
  - columnComments
  - notNull
showSchemaPrefix: false
schemaPrefixSeparator: "_"
outputMode: stdout

```

There are even unit tests validating that behaviour, see https://github.com/KarnerTh/mermerd/blob/b0d6fe710013fc083408f000371e96cc986673fc/analyzer/analyzer_test.go#L182-L219


I close this ticket for now, please double check that the ignored table names are correct. Feel free to reopen the issue if you are still facing the error.
